apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
  namespace: prod-curious
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        resources:
          requests:
            cpu: 0.5
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
        ports:
          - name: nfs
            containerPort: 2049
        securityContext:
          privileged: true