apiVersion: v1
kind: Service
metadata:
  name: precisely-blogs-letsencrypt-svc
  namespace: prod-curious
  labels:
    app: letsencrypt-precisely-blogs
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
  selector:
    name: letsencrypt-precisely-blogs
    role: cert-app