apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blogs-nginx
  namespace: prod-curious
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blogs-nginx
    spec:
      volumes:
      - name: configmap-volume
        configMap:
          name: nginx-config-precisely-blogs
      - name: letsencrypt-cert
        secret:
          secretName: cert-blog.precise.ly
      containers:
      - name: nginx
        image: nginx:1.11.12-alpine
        ports:
          - containerPort: 80
          - containerPort: 443
        volumeMounts:
          - name: configmap-volume
            mountPath: /etc/nginx/conf.d
            readOnly: true
          - name: letsencrypt-cert
            mountPath: /etc/nginx/nginx-ssl