apiVersion: v1
kind: Service
metadata:
  name: letsencrypt-svc-precisely
  namespace: prod-curious
  labels:
    app: letsencrypt-precisely
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
  selector:
    name: letsencrypt-precisely
    role: cert-app