apiVersion: v1
kind: PersistentVolume
metadata:
  name: curious-pv-nfs
  namespace: prod-curious
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: prod-curious
    name: curious-pvc-nfs
  nfs:
    path: "/"
    server: 10.51.251.6  # Cluster IP of nfs-service