apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch
  namespace: prod-curious
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        tier: backend
    spec:
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: curious-pvc-nfs
      containers:
      - name: elasticsearch
        image: elasticsearch:1.7-alpine
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
        env:
        - name: HTTP_ENABLE
          value: "true"
        ports:
          - containerPort: 9300
        volumeMounts:
          - name: elasticsearch-data
            mountPath: /usr/share/elasticsearch/data
            subPath: elasticsearch/data
