# Refer to the Github Repo: https://github.com/ployst/docker-letsencrypt

kind: ReplicationController
apiVersion: v1
metadata:
  name: letsencrypt
  namespace: prod-curious
spec:
  replicas: 1
  selector:
    name: letsencrypt
    role: cert-app
  template:
      metadata:
        name: letsencrypt-rc
        labels:
          name: letsencrypt
          role: cert-app
      spec:
        containers:
        - name: letsencrypt
          image: ployst/letsencrypt:0.3.0
          resources:
            requests:
              cpu: 0.2
              memory: 0.5Gi
            limits: # Pod cannot obtain resources more than the limits specified.
              cpu: 0.5
              memory: 0.5Gi
          env:
          - name: EMAIL
            value: developers@causecode.com
          - name: DOMAINS
            value: wearecurio.us
          - name: DEPLOYMENTS
            value: nginx
          - name: NAMESPACE
            value: prod-curious
          - name: SECRET_NAME # Name of the Secret in which certificate key information will be stored.
            value: cert-wearecurio.us
          ports:
            - containerPort: 80