apiVersion: v1
kind: Service
metadata:
  name: letsencrypt-svc
  namespace: prod-curious
  labels:
    app: letsencrypt
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
  selector:
    name: letsencrypt
    role: cert-app